name: hello-world

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository code
        uses: actions/checkout@v2

      - name: Say-hello
        run: make say-hello

